# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 12:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e')),
                ('employment_date', models.DateField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u0435\u043c\u0430 \u043d\u0430 \u0440\u0430\u0431\u043e\u0443')),
                ('date_of_dismissal', models.DateField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043f\u0440\u0438\u0435\u043c\u0430 \u043d\u0430 \u0440\u0430\u0431\u043e\u0443')),
                ('date_birth', models.DateField(verbose_name='\u0414\u0430\u0442\u0430 \u0440\u043e\u0436\u0434\u0435\u043d\u0438\u044f')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430 \u0434\u043e\u043b\u0436\u0435\u043d \u0431\u044b\u0442\u044c \u0432\u0432\u0435\u0434\u0435\u043d \u0432 \u0444\u043e\u0440\u043c\u0430\u0442\u0435: \xab+999999999\xbb. \u0414\u043e\u043f\u0443\u0441\u043a\u0430\u0435\u0442\u0441\u044f \u0434\u043e 15 \u0446\u0438\u0444\u0440.', regex='^\\+?1?\\d{9,15}$')])),
                ('position', models.SmallIntegerField(choices=[(0, '\u0410\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440'), (1, '\u0410\u043d\u0430\u043b\u0438\u0442\u0438\u043a'), (2, '\u0410\u0443\u0434\u0438\u0442\u043e\u0440'), (3, '\u0410\u0443\u043a\u0446\u0438\u043e\u043d\u0438\u0441\u0442'), (4, '\u0411\u0438\u0440\u0436\u0435\u0432\u043e\u0439 \u043c\u0430\u043a\u043b\u0435\u0440'), (5, '\u0411\u0438\u0440\u0436\u0435\u0432\u0438\u043a'), (6, '\u0411\u0443\u0445\u0433\u0430\u043b\u0442\u0435\u0440'), (7, '\u0411\u0443\u0445\u0433\u0430\u043b\u0442\u0435\u0440-\u0430\u0443\u0434\u0438\u0442\u043e\u0440'), (8, '\u0414\u0438\u043b\u0435\u0440'), (9, '\u0414\u0438\u0441\u043f\u0435\u0442\u0447\u0435\u0440'), (11, '\u0414\u043e\u043a\u0443\u043c\u0435\u043d\u0442\u043e\u0432\u0435\u0434'), (12, '\u0418\u043d\u0436\u0435\u043d\u0435\u0440'), (13, '\u0411\u0440\u043e\u043a\u0435\u0440')])),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.Department', verbose_name='\u0420\u0435\u0433\u0438\u043e\u043d')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
